name: checkout

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      run: |
        set -x
        git config --global user.email "h.nakamura0903@gmail.com"
        git config --global user.name "nekoTheShadow"
        cd $GITHUB_WORKSPACE
        git clone https://nekoTheShadow:${{ secrets.GITHUB_TOKEN }}@github.com/nekoTheShadow/github-actions-playground
        cd github-actions-playground
        date >> date.txt
        git add -A
        git commit -m 'commit by github actions'
        git push origin master
