name: hugo

on: [push]

jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
    - name: install-hugo
      run: sudo snap install hugo
    - name: checkout
      run: git clone --recursive -b admin https://github.com/nekoTheShadow/nekoTheShadow.github.io.git
    - name: build
      run: |
        cd nekoTheShadow.github.io
        hugo -v
