name: hugo

on: [push]

jobs:
  hugo:
    runs-on: ubuntu-latest
    steps:
    - name: install-hugo
      run: snap install hugo
    - name: check
      run: |
        which hugo
        hugo version
